# Generated by Django 3.0.5 on 2020-04-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('street_name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=300)),
                ('postal_code', models.IntegerField(max_length=4)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('open_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
